language: php
php:
- 7
- 5.6
- 5.5
- 5.4
- 5.3
- hhvm
matrix:
  allow_failures:
  - php: hhvm
before_script:
- echo "memory_limit=2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
- composer selfupdate
- composer clearcache
- composer install --no-interaction --dev --prefer-dist
script:
- "./vendor/bin/phpunit"
notifications:
  email:
    recipients:
    - david@verholen.com
    on_success: never
    on_failure: always
